### ISSUE TITLE
Please release under a F/OSS license

### ISSUE THREAD

**Issue by mr-c** [nanoporetech/minknow_api#12]
This will allow packaging of minknow_api for Linux distributions like Debian, (bio)conda, and others.

As for the  current LICENSE.txt, I can find no mention of a "Terms and Conditions of the Nanopore Community" document at https://nanoporetech.com/ 

I see that https://myaccount.nanoporetech.com/registration/users/details links to https://nanoporetech.com/commercial_information with the text "Nanopore Community Terms & Conditions", but that page lists 10 different documents, none of them named "Nanopore Community Terms & Conditions"

The closest match is the "Nanopore Product Terms & Conditions" at https://nanoporetech.com/sites/default/files/s3/terms/Nanopore-product-terms-and-conditions-nov2018-v2.pdf , but that gives no right of (re)distribution for any software, and under section 2.2.2m it specifically excludes the right to 
>  redistribute, encumber, sell, rent, lease, sublicense or otherwise transfer rights to Goods or Software

Without a clear license that at least allows for (re)distribution, even https://pypi.org/project/minknow-api/ does not have to right to (re)distribute the minknow_api.

Thanks!

**Comment by thequicksort** [comment]
Big +1 on this, the licensing ambiguity is hampering my team as well. 

@mr-c 
Thank you for your diligence in documenting the license hunt. I had also tried finding the licensing info without success. Inspired by your post, I started digging into the licensing more, and I believe the intended license for the MinknowAPI is the [Oxford Nanopore Technologies, Ltd. Public License Version 1.0](https://github.com/nanoporetech/flappie/blob/master/LICENCE.txt)
. My reason for believing this is [the 28 November 2018 commit](https://github.com/nanoporetech/flappie/commit/131f075dc240c5c28b0647670385361e4993651f#diff-34f90f739ec8d68766717821b16f670c55267082d8a6830d75d747f4430bb08dL336) on the Flappie package, which includes a change to the license file updating links from [http://nanoporetech.com](http://nanoporetech.com) to [https://github.com/nanoporetech/flappie/blob/master/LICENCE.txt](https://github.com/nanoporetech/flappie/blob/master/LICENCE.txt). Since the MinknowAPI license file references the same defunct URL, perhaps it's also meant to reference the same license? 

Assuming the MinknowAPI's intended license is indeed the ONT Public License, is that license permissive enough to qualify it as F/OSS, or is it otherwise sufficiently permissive for your use cases?

**Comment by jorj1988** [comment]
Hello,

We are working internally to sort this out - I hope to have a new release out shortly.

Thanks,
- George

**Comment by mr-c** [comment]
> Assuming the MinknowAPI's intended license is indeed the ONT Public License, is that license permissive enough to qualify it as F/OSS, or is it otherwise sufficiently permissive for your use cases?

FYI: The ONT Public License is not an approved OSI open source license, nor does it meet Debian's [criteria](https://www.debian.org/social_contract#guidelines)

https://opensource.org/licenses/alphabetical

The biggest problem for Debian is that the ONT Public License restricts field of use ("research purposes only") violates DFSG # 6 "No Discrimination Against Fields of Endeavor":

https://github.com/nanoporetech/flappie/blob/4de542ffe4e476077a6d061d40b48b3e87ae47c6/LICENCE.txt#L102

@jorj1988 Thanks for the update! Any word as to which new license will be chosen? I personally recommend the Apache 2.0 license.

**Comment by mr-c** [comment]
Relevant commit: https://github.com/nanoporetech/minknow_api/commit/50955d34552be129ea5f6aeef1262b8007cf7ee1

Thanks!
