### ISSUE TITLE
can we specify  toml for a sequencing run via the API?

### ISSUE THREAD

**Issue by neuropathbasel** [nanoporetech/minknow_api#30]
Is there a way to specify toml for a sequencing run via the API? We could specify a particular toml for a playback / simulation run.
Looking forward to your reply.
Best wishes
Claus

**Comment by jorj1988** [comment]
The output of the `find_protocol` function in the start_protocol example is a toml filename without the ".toml" extension, so:

Here:
https://github.com/nanoporetech/minknow_api/blob/master/python/examples/start_protocol.py#L432

You could specify your own toml reference rather than searching for the right protocol to start. It might help to dump this identifier in the existing protocol in order to get an idea for how the identifier is presented.

I hope that helps.

**Comment by neuropathbasel** [comment]
Thanks a lot, will try a.s.a.p! Closing issue.
